- name: Install Java
  package:
    name: "{{ mc_java_package }}"
    state: present

- name: Add group minecraft.
  group:
    name: minecraft
    state: present

- name: Add user minecraft.
  user:
    name: minecraft
    shell: /bin/bash
    home: /opt/paper
    group: minecraft

- name: Prepare working directory for paperspigot
  file:
    path: /opt/paper/run/
    state: directory
    owner: minecraft
    group: minecraft
    mode: '755'

- name: Place paper.jar.
  copy:
    src: "{{ mc_paperspigot_file }}"
    dest: /opt/paper/run/paper.jar
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Accept EULA
  copy:
    src: eula.txt
    dest: /opt/paper/run/eula.txt
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Prepare paper.yml
  copy:
    src: paper.yml
    dest: /opt/paper/run/paper.yml
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Prepare server.properties
  template:
    src: server.properties.j2
    dest: /opt/paper/run/server.properties
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Install bukkit.yml
  copy:
    src: bukkit.yml
    dest: /opt/paper/run/bukkit.yml
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Install spigot.yml
  copy:
    src: spigot.yml
    dest: /opt/paper/run/spigot.yml
    owner: minecraft
    group: minecraft
  notify: "Restart Minecraft"

- name: Prepare systemd unit file
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: '644'
  notify: "Restart Minecraft"

- name: Activate new systemd file
  systemd:
    daemon_reload: yes

- name: Start and enable minecraft service
  service:
    name: minecraft
    state: started
    enabled: yes
