- name: Place various plugin files
  copy:
    src: "{{ item.value }}"
    dest: "/opt/paper/run/plugins/{{ item.key }}"
    owner: minecraft
    group: minecraft
  notify: Restart Minecraft
  loop: "{{ mc_plugins | dict2items }}"
