- name: Create Scripting Directory
  file:
    path: /opt/paper/scr/
    state: directory
    owner: minecraft
    group: minecraft

- name: Create Backup Directory
  file:
    path: /opt/paper/backup/
    state: directory
    owner: minecraft
    group: minecraft

- name: Prepare Backup Script
  template:
    src: backup_ng.sh.j2
    dest: /opt/paper/scr/backup_ng.sh
    owner: minecraft
    group: minecraft
    mode: "700"

- name: Create Backup Directory
  file:
    path: /opt/paper/backup_nfs/{{ mc_world_name }}
    state: directory
    owner: minecraft
    group: minecraft

- name: Crontab job for backup
  ansible.builtin.cron:
    name: "Backup {{ mc_world_name }}"
    user: minecraft
    minute: "45"
    hour: "03"
    job: "/opt/paper/scr/backup_ng.sh"
